import Head from "next/head";
import Header from "../components/Header/Header";
import { useDispatch } from "react-redux";
import { setInfo } from "../store/features/infoSlice";
import { useEffect } from "react";
import axios from "axios";

export default function Home() {
  const dispatch = useDispatch();

  useEffect(() => {
    const getInfo = async () => {
      try {
        const info = await axios.get(
          "https://raw.githubusercontent.com/javialcocer/test-json/main/data.json"
        );
        dispatch(setInfo(info.data));
      } catch (error) {
        console.log(error);
      }
    };
    getInfo();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </div>
  );
}
