import Head from "next/head";
import Header from "../components/header/Header";
import Navbar from "../components/navbar/Navbar";
import { useDispatch } from "react-redux";
import { setInfo } from "../store/features/infoSlice";
import { useEffect } from "react";
import axios from "axios";
import Main from "../components/main/Main";
import Footer from "../components/footer/Footer";
import NavbarMobile from "../components/mobile/navbar/NavbarMobile";
import HeaderMobile from "../components/mobile/header/HeaderMobile";
import MainMobile from "../components/mobile/main/MainMobile";
import {
  BrowserView,
  MobileView,
} from "react-device-detect";

export default function Home() {
  const dispatch = useDispatch();

  useEffect(() => {
    const getInfo = async () => {
      try {
        const info = await axios.get(
          "https://raw.githubusercontent.com/javialcocer/test-json/main/data.json"
        );
        dispatch(setInfo(info.data));
      } catch (error) {
        console.log(error);
      }
    };
    getInfo();
  }, []);

  return (
    <>
      <Head>
        <title>Hoteles XCARET</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BrowserView>
        <div>
          <Navbar />
          <Header />
          <Main />
          <Footer />
        </div>
      </BrowserView>
      <MobileView>
        <div>
          <NavbarMobile />
          <HeaderMobile />
          <MainMobile />
          <Footer />
        </div>
      </MobileView>
    </>
  );
}
